# Generated by Django 5.2.5 on 2025-08-19 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('class_id', models.AutoField(primary_key=True, serialize=False)),
                ('class_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Months',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_id', models.AutoField(primary_key=True, serialize=False)),
                ('sub_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('erp', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('middle_name', models.CharField(blank=True, max_length=20, null=True)),
                ('last_name', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=10)),
                ('dob', models.DateField()),
                ('address', models.TextField()),
                ('contact_number', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=100)),
                ('admission_date', models.DateField()),
                ('password', models.CharField(max_length=20)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.class')),
            ],
        ),
        migrations.CreateModel(
            name='StudentFees',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tuition_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('admission_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('exam_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('library_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('lab_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sports_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('computer_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('development_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('smart_class_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('identity_card_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('annual_day_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('transportation_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('caution_money', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fine', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('misc_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid')], max_length=10)),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.months')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.student')),
            ],
        ),
    ]
